# Site settings
title: John Culleton's Blog
#email: your-email@domain.com
description: "Software Development Thoughts"
baseurl: ""
url: "http://blog.johnculleton.com"

# Build settings
markdown: kramdown
permalink: pretty
